const { create } = require('xmlbuilder2');
const faker = require('faker-br');
const fs = require('fs');
const parseArgs = require('minimist')(process.argv.slice(2));

const emit = parseArgs.emit ?? '14899142000147';
const vTPrest = faker.random.float();
const idCTe = faker.phone.phoneNumber('############################################');

const doc = create({ version: "1.0", encoding: "UTF-8" })
    .ele('cteProc', { xmlns: "http://www.portalfiscal.inf.br/cte", versao: "3.00" })
        .ele('CTe', { xmlns: "http://www.portalfiscal.inf.br/cte" })
            .ele('infCte', {Id: "CTe" + idCTe, versao: "3.00"})
                .ele('ide')
                    .ele('cUF').txt(35).up()
                    .ele('cCT').txt('01072910').up()
                    .ele('CFOP').txt('5352').up()
                    .ele('natOp').txt('Prest. Serv. Estabelecimento Industrial').up()
                    .ele('mod').txt(57).up()
                    .ele('serie').txt(1).up()
                    .ele('nCT').txt('719263').up()
                    .ele('dhEmi').txt('2023-11-20T20:49:07-03:00').up()
                    .ele('tpImp').txt(1).up()
                    .ele('tpEmis').txt(1).up()
                    .ele('cDV').txt(8).up()
                    .ele('tpAmb').txt(1).up()
                    .ele('tpCTe').txt(0).up()
                    .ele('procEmi').txt(0).up()
                    .ele('verProc').txt('KMM CT-e - 20.0.45').up()
                    .ele('cMunEnv').txt('3550308').up()
                    .ele('xMunEnv').txt(faker.address.city()).up()
                    .ele('UFEnv').txt(faker.address.stateAbbr()).up()
                    .ele('modal').txt('01').up()
                    .ele('tpServ').txt(0).up()
                    .ele('cMunIni').txt('3507605').up()
                    .ele('xMunIni').txt(faker.address.city()).up()
                    .ele('UFIni').txt(faker.address.stateAbbr()).up()
                    .ele('cMunFim').txt('3550308').up()
                    .ele('xMunFim').txt(faker.address.city()).up()
                    .ele('UFFim').txt(faker.address.stateAbbr()).up()
                    .ele('retira').txt(1).up()
                    .ele('indIEToma').txt(1).up()
                    .ele('toma3')
                        .ele('toma').txt(0)
                    .up()
                .up()
            .up()  
        .ele('compl')
            .ele('xEmi').txt(faker.random.alpha({ count: 14, upcase: true})).up()
            .ele('xObs').txt(faker.lorem.words(50))
            .up()
        .up()
        .ele('emit')
            .ele('CNPJ').txt(emit).up() 
            .ele('IE').txt(faker.phone.phoneNumber('############')).up()
            .ele('xNome').txt(faker.company.companyName()).up()
            .ele('xFant').txt(faker.company.companyName()).up()            
            .ele('enderEmit')
            .ele('xLgr').txt(faker.address.streetName()).up()
            .ele('nro').txt(faker.random.number()).up()
            .ele('xBairro').txt(faker.random.word()).up()
            .ele('cMun').txt(faker.random.number()).up()
            .ele('xMun').txt(faker.address.city()).up()
            .ele('CEP').txt(faker.phone.phoneNumber('#######')).up()            
            .ele('UF').txt(faker.address.stateAbbr()).up()
            .ele('fone').txt(faker.phone.phoneNumber('##########')).up()
            .up()      
        .up()
        .ele('rem')
            .ele('CNPJ').txt(faker.br.cnpj()).up() 
            .ele('IE').txt(faker.phone.phoneNumber('############')).up()
            .ele('xNome').txt(faker.company.companyName()).up()
            .ele('xFant').txt(faker.company.companyName()).up()
            .ele('fone').txt(faker.phone.phoneNumber('##########')).up()            
            .ele('enderReme')
            .ele('xLgr').txt(faker.address.streetName()).up()
            .ele('nro').txt(faker.random.number()).up()
            .ele('xBairro').txt(faker.random.word()).up()
            .ele('cMun').txt(faker.random.number()).up()
            .ele('xMun').txt(faker.address.city()).up()
            .ele('CEP').txt(faker.phone.phoneNumber('#######')).up()            
            .ele('UF').txt(faker.address.stateAbbr()).up()
            .ele('cPais').txt(faker.random.number()).up()
            .ele('xPais').txt(faker.address.country()).up()
            .up()
            .ele('email').txt(faker.internet.exampleEmail()).up()
        .up()
        .ele('exped')
            .ele('CNPJ').txt(faker.br.cnpj()).up() 
            .ele('IE').txt(faker.phone.phoneNumber('############')).up()
            .ele('xNome').txt(faker.company.companyName()).up()
            .ele('fone').txt(faker.phone.phoneNumber('##########')).up()              
            .ele('enderExped')
            .ele('xLgr').txt(faker.address.streetName()).up()
            .ele('nro').txt(faker.random.number()).up()
            .ele('xCpl').txt(faker.random.word()).up()
            .ele('xBairro').txt(faker.random.word()).up()
            .ele('cMun').txt(faker.random.number()).up()
            .ele('xMun').txt(faker.address.city()).up()
            .ele('CEP').txt(faker.phone.phoneNumber('#######')).up()
            .ele('UF').txt(faker.address.stateAbbr()).up()
            .ele('cPais').txt(faker.random.number()).up()
            .ele('xPais').txt(faker.address.country()).up()
        .up().up()
        .ele('receb')
            .ele('CNPJ').txt(faker.br.cnpj()).up() 
            .ele('IE').txt(faker.phone.phoneNumber('############')).up()
            .ele('xNome').txt(faker.company.companyName()).up()       
            .ele('enderReceb')
            .ele('xLgr').txt(faker.address.streetName()).up()
            .ele('nro').txt(faker.random.number()).up()
            .ele('xBairro').txt(faker.random.word()).up()            
            .ele('cMun').txt(faker.random.number()).up()
            .ele('xMun').txt(faker.address.city()).up()
            .ele('CEP').txt(faker.phone.phoneNumber('#######')).up()
            .ele('UF').txt(faker.address.stateAbbr()).up()
            .ele('cPais').txt(faker.random.number()).up()
            .ele('xPais').txt(faker.address.country()).up()
        .up().up()
        .ele('dest')
            .ele('CNPJ').txt(faker.br.cnpj()).up() 
            .ele('IE').txt(faker.phone.phoneNumber('############')).up()
            .ele('xNome').txt(faker.company.companyName()).up()       
            .ele('enderDest')
            .ele('xLgr').txt(faker.address.streetName()).up()
            .ele('nro').txt(faker.random.number()).up()
            .ele('xBairro').txt(faker.random.word()).up()            
            .ele('cMun').txt(faker.random.number()).up()
            .ele('xMun').txt(faker.address.city()).up()
            .ele('CEP').txt(faker.phone.phoneNumber('#######')).up()
            .ele('UF').txt(faker.address.stateAbbr()).up()
            .ele('cPais').txt(faker.random.number()).up()
            .ele('xPais').txt(faker.address.country()).up()
        .up().up()
        .ele('vPrest')
            .ele('vTPrest').txt(vTPrest).up()
            .ele('vRec').txt(vTPrest).up()
            .ele('Comp')
            .ele('xNome').txt('Frete valor').up()
            .ele('vComp').txt(faker.random.float()).up()
        .up().up()
        .ele('imp')
            .ele('ICMS')
                .ele('ICMS00')
                    .ele('CST').txt('00').up()
                    .ele('vBC').txt(faker.random.number()).up()
                    .ele('pICMS').txt(faker.random.float()).up()
                    .ele('vICMS').txt(faker.random.float()).up()
            .up().up()
            .ele('vTotTrib').txt(faker.random.float()).up()
        .up()
        .ele('infCTeNorm')
            .ele('infCarga')
                .ele('vCarga').txt(faker.random.float()).up()
                .ele('proPred').txt('DIVERSOS').up()
                .ele('xOutCat').txt('PALLET').up()
                .ele('infQ')
                    .ele('cUnid').txt('01').up()
                    .ele('tpMed').txt('Peso Liquido').up()
                    .ele('qCarga').txt(faker.random.float()).up()
                .up()
                .ele('vCargaAverb').txt(faker.random.float()).up()
            .up()
            .ele('infDoc')
                .ele('infNFe')
                    .ele('chave').txt(faker.phone.phoneNumber('############################################')).up()
            .up().up()
            .ele('infModal', { versaoModal: "3.00" })
                .ele('rodo')
                    .ele('RNTRC').txt(faker.phone.phoneNumber('########'))
            .up().up().up().up()
        .ele('autXML')
            .ele('CNPJ').txt(faker.br.cnpj()).up()
        .up()
        .ele('infRespTec')
            .ele('CNPJ').txt(faker.br.cnpj()).up()
            .ele('xContato').txt(faker.name.findName()).up()
            .ele('email').txt(faker.internet.exampleEmail()).up()
            .ele('fone').txt(faker.phone.phoneNumber('############')).up()
        .up().up()
        .ele('infCTeSupl')
            .ele('qrCodCTe').txt('<![CDATA[ https://nfe.fazenda.sp.gov.br/CTeConsulta/qrCode?chCTe=35231014899142000147570010007192631010729108&tpAmb=1 ]]>')
        .up().up()
        .ele('Signature', { xmlns: 'http://www.w3.org/2000/09/xmldsig#'})
            .ele('SignedInfo').up()
            .ele('SignatureValue').up()
            .ele('KeyInfo').up()
        .up().up() 
            .ele('protCTe', { versao: "3.00"})  
            .ele('infProt', { xmlns: "http://www.portalfiscal.inf.br/cte"})
            .ele('tpAmb').txt(1).up()
            .ele('verAplic').txt('SP-CTe-2023-08-30-1').up()
            .ele('chCTe').txt(idCTe).up()
            .ele('dhRecbto').txt('2023-10-02T20:49:08-03:00').up()
            .ele('nProt').txt(faker.phone.phoneNumber('###############')).up()
            .ele('digVal').txt(faker.random.alpha(20)).up()
            .ele('cStat').txt(100).up()
            .ele('xMotivo').txt('Autorizado o uso do CT-e').up()
    .doc();

fs.writeFileSync('CTe' + idCTe + '.xml', doc.end({ prettyPrint: true }));